"use client";

import { ChevronDown, HelpCircle, Play } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { cn } from "@/lib/utils";

const FAQS = [
  {
    q: "How do candidates join an interview room?",
    a: "Candidates click a unique secure link generated by your team. They are placed in a quiet waiting lobby until an interviewer admits them. No account creation or installation required.",
  },
  {
    q: "Can multiple interviewers join the same room?",
    a: "Yes! Multiple interviewers can join simultaneously, observe the candidate's code execution in real time, and record shared or private evaluation notes.",
  },
  {
    q: "What programming languages are supported in the code editor?",
    a: "Camio supports JavaScript, TypeScript, Python, Java, C++, Go, Rust, Ruby, and SQL with syntax highlighting, auto-formatting, and execution output.",
  },
  {
    q: "How does the Instant Quick Preview work?",
    a: "The Quick Preview button in the top app bar bypasses auth requirements for testing purposes, allowing you to instantly view candidate and interviewer perspectives live.",
  },
  {
    q: "Is audio/video encrypted?",
    a: "Yes, all WebRTC video and audio streams are end-to-end encrypted using standard DTLS-SRTP security protocols.",
  },
];

export function DocsSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section id="docs" className="px-6 py-24 border-b border-border/40 relative bg-muted/10">
      <div className="mx-auto max-w-6xl space-y-16">
        <div className="text-center space-y-4">
          <Badge variant="outline" className="border-primary/40 text-primary">
            Documentation & FAQ
          </Badge>
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Everything you need to get started
          </h2>
          <p className="mx-auto max-w-2xl text-muted-foreground text-sm sm:text-base">
            Learn how Camio streamlines candidate waiting lobbies, real-time code evaluation, and collaborative whiteboard sessions.
          </p>
        </div>

        {/* 3 Step Workflow Overview */}
        <div className="grid md:grid-cols-3 gap-6">
          <Card className="p-6 space-y-4 border-border/70 bg-background/80 backdrop-blur-md rounded-2xl">
            <div className="h-10 w-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center font-bold text-sm">
              01
            </div>
            <h3 className="font-bold text-base">1. Create an Interview Room</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Generate a room link in seconds from your dashboard or pick from pre-built question templates.
            </p>
          </Card>

          <Card className="p-6 space-y-4 border-border/70 bg-background/80 backdrop-blur-md rounded-2xl">
            <div className="h-10 w-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center font-bold text-sm">
              02
            </div>
            <h3 className="font-bold text-base">2. Conduct Live Interview</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Video call, write and execute code in real-time, sketch diagrams on the shared whiteboard, and keep private notes.
            </p>
          </Card>

          <Card className="p-6 space-y-4 border-border/70 bg-background/80 backdrop-blur-md rounded-2xl">
            <div className="h-10 w-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center font-bold text-sm">
              03
            </div>
            <h3 className="font-bold text-base">3. Review & Submit Scorecard</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Evaluate problem-solving skills, view execution metrics, and share feedback with your hiring committee.
            </p>
          </Card>
        </div>

        {/* Accordion FAQ */}
        <div className="max-w-3xl mx-auto space-y-4 pt-4">
          <h3 className="text-xl font-bold text-center mb-6">Frequently Asked Questions</h3>
          {FAQS.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div
                key={faq.q}
                className="rounded-2xl border border-border/70 bg-background/80 backdrop-blur-md overflow-hidden transition-all"
              >
                <button
                  onClick={() => setOpenIndex(isOpen ? null : idx)}
                  className="flex items-center justify-between w-full p-5 text-left text-sm font-semibold hover:text-primary transition-colors gap-4"
                >
                  <span className="flex items-center gap-2.5">
                    <HelpCircle className="h-4 w-4 text-primary shrink-0" />
                    {faq.q}
                  </span>
                  <ChevronDown
                    className={cn("h-4 w-4 text-muted-foreground shrink-0 transition-transform duration-200", isOpen && "rotate-180 text-primary")}
                  />
                </button>
                {isOpen && (
                  <div className="px-5 pb-5 pt-0 text-xs text-muted-foreground leading-relaxed border-t border-border/40 mt-1">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        <div className="flex justify-center pt-4">
          <Link
            href="/candidate/demo-room"
            className={cn(buttonVariants({ variant: "outline", size: "lg" }), "gap-2 rounded-xl text-xs font-semibold")}
          >
            <Play className="h-4 w-4 text-primary" />
            <span>Try Candidate Demo Room Now</span>
          </Link>
        </div>
      </div>
    </section>
  );
}
